import Link from 'next/link';
import { ArrowRight, Activity, BrainCircuit, Radar, ShieldCheck, Sparkles, TriangleAlert } from 'lucide-react';

const capabilities = [
  ['Observe', 'Replay validated CICIDS2017 and UNSW-NB15 flows as live telemetry.'],
  ['Detect', 'Combine supervised classification with unknown-behaviour anomaly scoring.'],
  ['Respond', 'Prioritize alerts, correlate incidents, and record every response decision.'],
];

export default function HomePage() {
  return <main className="landing-shell min-h-screen overflow-hidden text-[#e8f1e9]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <Link href="/" className="flex items-center gap-3 font-sans font-bold tracking-tight"><span className="grid h-10 w-10 place-items-center rounded-full border border-[#71a889]/40 bg-[#18342c]"><ShieldCheck className="h-5 w-5 text-[#a4d9ad]" /></span><span>NETSHIELD <em className="not-italic text-[#d88954]">AI</em></span></Link>
      <div className="hidden gap-7 text-sm text-[#a9b8aa] md:flex"><a href="#system">System</a><a href="#model">Intelligence</a><a href="#workflow">Workflow</a></div>
      <Link href="/login" className="rounded-full border border-[#8da590]/30 px-4 py-2 text-sm transition hover:border-[#a4d9ad] hover:text-[#a4d9ad]">Operator sign in</Link>
    </nav>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:pb-32 lg:pt-24">
      <div className="relative z-10"><p className="mb-6 flex items-center gap-2 font-mono text-xs uppercase tracking-[.22em] text-[#a4d9ad]"><span className="h-2 w-2 rounded-full bg-[#a4d9ad]" /> Network defence observatory</p><h1 className="max-w-3xl font-sans text-5xl font-semibold leading-[.98] tracking-[-.055em] text-[#f1f6ef] md:text-7xl">See the shift<br />before the breach.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#b4c1b4]">NetShield turns trusted network datasets into a practical SOC workspace: monitor flow behaviour, expose risky patterns, and carry an investigation from signal to report.</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-[#a4d9ad] px-6 py-3 font-semibold text-[#0b1b16] transition hover:bg-[#c4ebba]">Create operator profile <ArrowRight className="h-4 w-4" /></Link><a href="#system" className="inline-flex items-center gap-2 rounded-full border border-[#728c78] px-6 py-3 font-medium text-[#e8f1e9] hover:border-[#a4d9ad]">Explore the system</a></div></div>
      <div className="relative min-h-[380px] rounded-[2rem] border border-[#597262]/50 bg-[#10241e]/70 p-6 shadow-2xl shadow-black/30"><div className="absolute inset-0 rounded-[2rem] opacity-40 [background-image:radial-gradient(#85aa8f_1px,transparent_1px)] [background-size:24px_24px]" /><div className="relative flex items-center justify-between font-mono text-[11px] uppercase tracking-widest text-[#a9b8aa]"><span>Flow field / east region</span><span className="text-[#a4d9ad]">live-safe replay</span></div><div className="relative mt-8 grid grid-cols-2 gap-3"><Metric label="Flows inspected" value="24,918" /><Metric label="Risk surface" value="07.4" accent /><Metric label="Alert latency" value="0.8 s" /><Metric label="Model consensus" value="96.2%" /></div><div className="absolute bottom-6 left-6 right-6 rounded-2xl border border-[#d88954]/30 bg-[#192c25]/90 p-4"><div className="flex items-center gap-3"><TriangleAlert className="h-5 w-5 text-[#d88954]" /><div><p className="text-sm font-semibold">Unusual SSH recurrence</p><p className="mt-1 font-mono text-xs text-[#a9b8aa]">98.51.100.44 → asset/edge-04 · high confidence</p></div></div></div></div>
    </section>
    <section id="system" className="border-y border-[#5b7060]/30 bg-[#102019] py-20"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="mb-12 flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#d88954]">A complete loop</p><h2 className="mt-3 text-3xl font-semibold tracking-tight md:text-4xl">From network flow to an accountable response.</h2></div><p className="max-w-md text-[#a9b8aa]">Every interface is built around an analyst’s reasoning process—not a generic dashboard.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-[#597262]/40 bg-[#597262]/40 md:grid-cols-3">{capabilities.map(([name, body], index) => <article key={name} className="bg-[#102019] p-7"><span className="font-mono text-xs text-[#d88954]">0{index + 1}</span><h3 className="mt-10 text-2xl font-semibold">{name}</h3><p className="mt-3 leading-7 text-[#a9b8aa]">{body}</p></article>)}</div></div></section>
    <section id="model" className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-2 lg:px-10"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-[#a4d9ad]">Hybrid detection</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Known threats, unfamiliar behaviour.</h2><p className="mt-6 max-w-xl leading-8 text-[#a9b8aa]">XGBoost identifies learned attack classes while Isolation Forest highlights statistically rare activity. Their evidence is shown alongside confidence, risk, and reason—not hidden behind a black box.</p></div><div className="grid gap-4 sm:grid-cols-2"><Feature icon={BrainCircuit} title="Classification" text="Binary and multiclass attack predictions with measured validation metrics." /><Feature icon={Radar} title="Anomaly field" text="Unsupervised scoring for deviations the labelled datasets did not teach." /><Feature icon={Activity} title="Risk narrative" text="A clear 0–100 score linked to confidence, impact, recurrence, and severity." /><Feature icon={Sparkles} title="Evidence trail" text="Reports, audit events, and incident notes remain visible end to end." /></div></section>
    <section id="workflow" className="mx-auto max-w-7xl px-6 pb-20 lg:px-10"><div className="rounded-[2rem] border border-[#5b7060]/40 bg-[#18342c] p-8 md:p-12"><p className="font-mono text-xs uppercase tracking-[.2em] text-[#d88954]">Ready for review</p><div className="mt-5 flex flex-wrap items-end justify-between gap-8"><div><h2 className="text-3xl font-semibold tracking-tight">A defensible security demo, not a theatre of alerts.</h2><p className="mt-3 max-w-2xl text-[#bfd0c1]">Safe traffic replay, auditable simulated response actions, and optional administrator-approved webhook integrations.</p></div><Link href="/register" className="rounded-full bg-[#e8f1e9] px-6 py-3 font-semibold text-[#102019]">Enter NetShield</Link></div></div></section>
  </main>;
}
function Metric({label, value, accent}) { return <div className={`rounded-xl border p-4 ${accent ? 'border-[#d88954]/40 bg-[#d88954]/10' : 'border-[#597262]/40 bg-[#132a22]/70'}`}><p className="font-mono text-[10px] uppercase tracking-wider text-[#a9b8aa]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>; }
function Feature({icon: Icon, title, text}) { return <div className="rounded-2xl border border-[#597262]/40 bg-[#132a22] p-5"><Icon className="h-5 w-5 text-[#d88954]" /><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#a9b8aa]">{text}</p></div>; }
